package com.harnet.whatisthedistance.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
class Station(
    @ColumnInfo(name = "station_id")
    val id: Int,
    @ColumnInfo(name = "station_name")
    val name: String,
    @ColumnInfo(name = "name_slug")
    val name_slug: String,
    @ColumnInfo(name = "latitude")
    val latitude: String?,
    @ColumnInfo(name = "longitude")
    val longitude: String?,
    @ColumnInfo(name = "hits")
    val hits: String,
    @ColumnInfo(name = "ibnr")
    val ibnr: String?,
    @ColumnInfo(name = "city")
    val city: String,
    @ColumnInfo(name = "region")
    val region: String,
    @ColumnInfo(name = "country")
    val country: String,
    @ColumnInfo(name = "localised_name")
    val localised_name: String?
){
    @PrimaryKey(autoGenerate = true) //autogenerated id for each instance
    var uuid: Int = 0
}